[project]
name = "reyserver"
version = "1.1.288"
description = "Backend asynchronous server integration API framework built on FastAPI."
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
keywords = [
    "rey",
    "reyxbo",
    "server",
    "backend",
    "fastapi",
    "API",
    "async",
    "asynchronous",
    "cache",
    "redis",
    "file",
    "link",
    "public",
    "redirect",
    "RESTful",
]
authors = [
    {name = "Rey", email = "reyxbo@163.com"}
]
dependencies = [
    "fastapi[standard]",
    "fastapi-cache2[redis]",
    "reyclient",
    "reydb",
    "reykit",
    "uvicorn[standard]",
]

[project.urls]
Homepage = "https://reyxbo.com:2/release/python/reyserver"
Repository = "https://github.com/reyxbo/reyserver-py.git"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
